# Generated by Django 4.2.2 on 2023-06-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=8)),
                ('mobile', models.CharField(max_length=10)),
                ('date_of_join', models.DateField(auto_now_add=True)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('post', models.TextField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=10)),
            ],
        ),
    ]
