# Generated by Django 4.2.2 on 2023-06-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_task', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('employee_id', models.CharField(max_length=10)),
                ('target_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.CharField(max_length=30),
        ),
    ]
