# Generated by Django 4.2.2 on 2023-06-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0004_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='employee_id',
            new_name='employee_name',
        ),
    ]
