# Generated by Django 4.2.2 on 2023-06-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0005_rename_employee_id_task_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
