# Generated by Django 4.2.2 on 2023-07-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0014_remove_messaging_chat_messaging_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaging',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
