# Generated by Django 4.2.2 on 2023-07-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0015_messaging_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messaging',
        ),
    ]
