# Generated by Django 4.2.2 on 2023-07-06 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0017_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
