# Generated by Django 4.2.2 on 2023-07-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0019_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='default.svg', upload_to='pics'),
        ),
    ]
