# Generated by Django 4.2.2 on 2023-07-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0020_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='https://www.cornwallbusinessawards.co.uk/wp-content/uploads/2017/11/dummy450x450.jpg', upload_to='pics/'),
        ),
    ]
