# Generated by Django 4.2.2 on 2023-07-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0023_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_join',
            field=models.DateField(blank=True, null=True),
        ),
    ]
