# Generated by Django 4.2.2 on 2023-07-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0027_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
