# Generated by Django 4.2.2 on 2023-07-14 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0029_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
